### ISSUE TITLE
public option for server startup

### ISSUE THREAD

**Issue by DarkSir23** [LTmadness/ValheimBetterServerConfig#12]
With the recent update to the dedicated server, they added -public as an option.  selecting 0 lets the server be a private dedicated server.   Is this something that can be added to the config settings?  I think once I turned the BSC back on, the public toggle stopped working.

**Comment by LTmadness** [comment]
Hi, it should already be in config (added in v0.0.60) if its not there I need to look into this issue

**Comment by DarkSir23** [comment]
Is it the 'visable' option?

**Comment by LTmadness** [comment]
Yes

**Comment by DarkSir23** [comment]
Awesome.  I wasn't sure.  Thanks for the quick response.  Makes a world of difference in packet flooding issues.

**Comment by DarkSir23** [comment]
Actually it still looks like we're having issues.  Is there a way to verify that "visable=false" is actully triggering the the server the same way that "private=0" does from the command line?

**Comment by LTmadness** [comment]
I will look into it to make sire in a sec

**Comment by LTmadness** [comment]
should be fixed with new release (v0.0.70)
