### ISSUE TITLE
[Feature Request] Chat showing in console

### ISSUE THREAD

**Issue by RainyJimbo** [LTmadness/ValheimBetterServerConfig#14]
Would it be possible for the mod to log all chats done by players online so it would appear in the console?

**Comment by LTmadness** [comment]
will try to add it in next release

**Comment by LTmadness** [comment]
@RainyJimbo New release has the ability to display shout (/s) in console still working on full integration with whisper and say(v0.0.80 out now)

**Comment by LTmadness** [comment]
this will be fully implemented in next release

**Comment by LTmadness** [comment]
should be fully implamented in latest live release(v0.1.2)
