### ISSUE TITLE
Console commands not working on Dedicated linux server

### ISSUE THREAD

**Issue by hampton-matt** [LTmadness/ValheimBetterServerConfig#17]
I've loaded the mod onto a dedicated ubuntu (16.04) server with Bepinex (valheim pack) correctly installed. The mod works in changing the server settings such as removing the password and backing up world saves, but when it comes to the console commands they aren't working. 

The steam user I am testing with is an admin on the server but the only commands that appear are the default valheim ones.

Do I need to install something client side or is this possibly and issue when running on a dedicated linux server?

Thanks for the mod, works really well for the server config otherwise.

**Comment by hampton-matt** [comment]
![console output](https://user-images.githubusercontent.com/54047092/110396171-6f2ae100-8067-11eb-8b11-1b6a1a1e8390.PNG)

Just thought I'd show the Bepinex console output showing the mod being loaded

**Comment by hampton-matt** [comment]
![error console](https://user-images.githubusercontent.com/54047092/110398282-75bb5780-806b-11eb-9010-0af8f13e641d.PNG)

Also found this error after the server had loaded to the point of being able to connect to it

**Comment by LTmadness** [comment]
Hey, the console commands are run in the server console not, not in the
game( I asumed that as you said default commands work and there is none cor
server console without this mod), it also seems that something is causing
an error while creating background thread, will investigate and come back
to you

**Comment by hampton-matt** [comment]
Its a google cloud e2 standard - 2vcpu and 8gb ram. Ubuntu 16.04.7 LTS

**Comment by LTmadness** [comment]
Thanks, should have expected google cloud severs they always break stuff 🙄

**Comment by LTmadness** [comment]
@hampton-matt  could you get in touch with me on discord #LTmadness9705

**Comment by LTmadness** [comment]
with newest release the issue should be fixed (v0.0.90)
