### ISSUE TITLE
Version not changed in the release

### ISSUE THREAD

**Issue by BaHeK1994** [LTmadness/ValheimBetterServerConfig#19]
The latest release version is 0.0.90, but the .dll file is still 0.0.80
File link: https://github.com/LTmadness/ValheimBetterServerConfig/releases/download/v0.0.90/BetterServerConfig.zip
![изображение](https://user-images.githubusercontent.com/18642618/110786900-c0acb900-827d-11eb-92a0-603c514de1d1.png)
![изображение](https://user-images.githubusercontent.com/18642618/110787163-14b79d80-827e-11eb-89c1-706b5d587021.png)

md5sum: 429af4ff653f013b918e0cfa98a99c28  ValheimBetterServerConfig.dll

**Comment by LTmadness** [comment]
as it is minor issue I will address it with next release, I checked the file uploaded and it does have rest of the code updated, just as incorrect version

**Comment by LTmadness** [comment]
fixed in release v0.1.0
