### ISSUE TITLE
Typo/Bug:- Please don't use ?? as its causing a error

### ISSUE THREAD

**Issue by Energritz** [LTmadness/ValheimBetterServerConfig#28]
Mod Version: 0.1.1
Bepinex Ver: 5.9.0
OS: Ubuntu Server 20.10

How to reproduce: I simply just shutdown the server via ssh, with the shutdown command, server did shutdown successfully.

Issue: Not sure if this is a bug or a typo that was missed, but upon shutting down the server the following lines are displayed
right at the end of the shutdown, last 2 lines in the console:

[Info   :   Console] Please don't use  as its causing error, please report it on https://github.com/LTmadness/ValheimBetterServerConfig, please include input command used
Please don't use  as its causing error, please report it on https://github.com/LTmadness/ValheimBetterServerConfig, please include input command used

It's saying please don't use "something" as its causing an error. I guessing don't use a certain command is important, but its missing from here, and i don't really feel safe knowing i shouldn't use a command but don't know which.
Again this is probably a typo, but figured it should be reported.

**Comment by LTmadness** [comment]
thank you will be fixed before next release

**Comment by LTmadness** [comment]
should be fixed in latest live release(v0.1.2)
