### ISSUE TITLE
Missing commands in help list

### ISSUE THREAD

**Issue by KairuByte** [LTmadness/ValheimBetterServerConfig#34]
I've noticed that not all commands are listed in the help list. Ban being a very obvious one. I don't have a full list at the moment, but you can test this by simply running the help command and comparing it's output to the methods available in code.

**Comment by LTmadness** [comment]
Hey, have you tried multiple pages, with current release its not particularly obvious that there more then one page of commands?

**Comment by KairuByte** [comment]
Yeah, I grabbed a screen of all three, though it isnt 100% clean:
![image](https://user-images.githubusercontent.com/393806/134708258-f3790637-686a-4c59-9388-32fb9d383770.png)

**Comment by KairuByte** [comment]
Actually, looking through it could be that help is indexing at 1, and the list is indexed at 0.

**Comment by LTmadness** [comment]
just so you know you can disable double lines by changing one setting in bepinex config(detail description in readMe file), I think I found whats causing the issue its skipping first page
