### ISSUE TITLE
Uncertain how to safely launch multiple servers on the same machine

### ISSUE THREAD

**Issue by forrester-marc** [LTmadness/ValheimBetterServerConfig#35]
Without ValheimBetterServerConfig I simply launch the server with different command line arguments to modify the world name and port number, but this mod overrides those settings from a single .cfg file.  I could use batch files to copy different .cfg files into place before launching, but then most server instances would have settings in memory that conflict with those on the disk which seems like a Bad Thing.

Is it best to simply have a separate copy of the server application and plugins for each world file?

**Comment by LTmadness** [comment]
I would suggest separate copy
