### ISSUE TITLE
Ability to run multiple servers

### ISSUE THREAD

**Issue by ReallyNotBad** [LTmadness/ValheimBetterServerConfig#5]
Hi,

currently I am running 2 seperate worlds on one server machine. Is this still possible with this mod? As far I can see it changes the port -> so both servers restart with the same port?

Thank you

**Comment by LTmadness** [comment]
you can choose what port you use so yes you can run multiple servers on one mashine

**Comment by ReallyNotBad** [comment]
I thought there is a way to have only one install directory.
But I will copy the server dir. So I have different configuration files.

thanks
