### ISSUE TITLE
Exception on startup, MissingMethod

### ISSUE THREAD

**Issue by ReallyNotBad** [LTmadness/ValheimBetterServerConfig#6]
Hi,

currently my dedicated server can't start with this plugin enabled.

[Error  : Unity Log] MissingMethodException: void ZNet.SetServerHost(string,int)
Stack trace:
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ParseServerArguments>(FejdStartup)
FejdStartup.Awake () (at <c75b626e86524acb99df7802e0378a36>:0)

MissingMethodException: void ZNet.SetServerHost(string,int)
  at (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ParseServerArguments>(FejdStartup)
  at FejdStartup.Awake () [0x000f0] in <c75b626e86524acb99df7802e0378a36>:0

**Comment by LTmadness** [comment]
I'm investigating, It seems that Valheim update broke the mod

**Comment by LTmadness** [comment]
[ValheimBetterServerConfig.zip](https://github.com/LTmadness/ValheimBetterServerConfig/files/6070213/ValheimBetterServerConfig.zip)

this should work it has the hot fix

**Comment by LTmadness** [comment]
The Hotfix was released on Git as well as Nexusmods and Thunderstore

**Comment by ReallyNotBad** [comment]
looks like this worked for me.

Can't test to connect to the server right now. But this should work I think.

Thank you
